### ISSUE TITLE
Support button gets replaced by delegation status

### ISSUE THREAD

**Issue by oliverbarnes** [liquidvotingio/decidim-module-liquidvoting#12]
Weirdly, after the support button is hit the delegation status appear on its place 🤔 this was already happening before the styling changes, fwiw

<img width="340" alt="Screen Shot 2020-10-29 at 2 36 00 PM" src="https://user-images.githubusercontent.com/21290/97588966-e931c600-19f4-11eb-82af-0a2a046af88f.png">

**Comment by oliverbarnes** [comment]
related to #9

**Comment by jinjagit** [comment]
We may not need to worry about this, as we might be hiding the support button and using our own 'in favor / 'against' buttons.

**Comment by oliverbarnes** [comment]
good question. but even if we do use our own button and ditch the original one, I think we should probably stick with the same vocabulary used by Decidim, as to not mess with their domain design too much. We want this to be a drop-in feature into existing processes. WDYT?

**Comment by jinjagit** [comment]
Actually, the 'support' or 'already supported' button (whichever should be visible) disappear after being clicked, but reappear on page refresh. This is somewhat separate to the delegation message duplication (which I think I have a fix for)...
![no_button](https://user-images.githubusercontent.com/3944042/97596553-bdb2d980-19fc-11eb-8ed9-111d88d491c6.png)

**Comment by davefrey** [comment]
This is incidentally fixed in the latest master. 

Also I double-checked we're not changing Decidim translation values (Decidim left, our module right):
```yaml
        vote_button:				        vote_button:
          already_voted: Already supported	          already_voted: Already supported
          already_voted_hover: Withdraw suppo	          already_voted_hover: Withdraw suppo
          maximum_votes_reached: Support limi	          maximum_votes_reached: Support limi
          no_votes_remaining: No supports rem	          no_votes_remaining: No supports rem
          vote: Support				          vote: Support
					      >	          vote_delegated: Support
          votes_blocked: Supports disabled	          votes_blocked: Supports disabled
```
I'll close the issue.
